/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import Data.BOQ;
import Data.ComponentOfBOQ;
import Data.OpenFile;
import Data.SaveToFile;
import java.awt.Color;
import java.text.DecimalFormat;
import java.util.Iterator;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SpinnerListModel;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Włosek
 */
public class Add extends javax.swing.JFrame {

    DefaultTableModel modelOfTable = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            if ((column == 5) || (column == 6)) {
                return false;
            }
            return true;
        }
    };
    DecimalFormat df = new DecimalFormat("#0.00");
    BOQ listOfQuantity = new BOQ();
    int selectedRow;
    int guard = 0;

    /**
     * Creates new form Add
     */
    public Add() {
        initComponents();

        modelOfTable.addColumn("Nazwa pozycji obmiarowej");
        modelOfTable.addColumn("Jednostka");
        modelOfTable.addColumn("Cena jednostkowa [zł]");
        modelOfTable.addColumn("Ilość jednostek ");
        modelOfTable.addColumn("Narzut[%]");
        modelOfTable.addColumn("Wartość robót [zł]");
        modelOfTable.addColumn("WW");

        
        modelOfTable.addTableModelListener(new TableModelListener() {

            @Override
            public void tableChanged(TableModelEvent e) {
                tableBOQ.setBackground(Color.WHITE);
                try {
                    if (guard == 1) {
                        return;
                    }
                    if (e.getType() == -1) {
                        return;
                    }
                    if ((e.getColumn() == 5) || (e.getColumn() == 6)) {
                        return;
                    }
                    System.out.println(e.getType());
                    
                    listOfQuantity.editList(tableBOQ, e.getColumn(), e.getLastRow());
                    refreshAmounts();
                    refreshAmount();

                    genWW();
                } catch (NumberFormatException exept) {
                    JOptionPane.showMessageDialog(null, "Błędnie wprowadzona wartość\n\nError: " + e);
                    tableBOQ.setBackground(Color.red);
                }

            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tableBOQ = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        nameField = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        unitField = new javax.swing.JTextField();
        rateField = new javax.swing.JTextField();
        quantityField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        netto = new javax.swing.JLabel();
        brutto = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        nameSR = new javax.swing.JLabel();
        valueSRField = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tax = new javax.swing.JSpinner();
        overheadLabel = new javax.swing.JLabel();
        marginLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Plik = new javax.swing.JMenu();
        Nowy = new javax.swing.JMenuItem();
        Open = new javax.swing.JMenuItem();
        Zapisz = new javax.swing.JMenuItem();
        Wyjście = new javax.swing.JMenuItem();
        Narzędzia = new javax.swing.JMenu();
        generujTabele = new javax.swing.JMenuItem();
        Pomoc = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(0, 0));

        tableBOQ.setModel(modelOfTable);
        tableBOQ.setColumnSelectionAllowed(true);
        tableBOQ.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tableBOQ.setRowHeight(20);
        tableBOQ.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableBOQ.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tableBOQ);
        tableBOQ.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dodaj/Usuń pozycję:"));
        jPanel1.setToolTipText("");
        jPanel1.setName(""); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(374, 211));

        nameField.setColumns(20);
        nameField.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        nameField.setRows(4);
        jScrollPane1.setViewportView(nameField);

        jLabel4.setText("Nazwa pozycji obmiarowej:");

        jLabel1.setText("Jednostka:");

        jLabel2.setText("Cena jednostkowa:");

        jLabel3.setText("Ilość jednostek:");

        addButton.setText("Dodaj");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        delete.setText("Usuń");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rateField, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(unitField, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(quantityField, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(127, 127, 127)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(unitField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(addButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(delete))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(0, 0, 0))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Wyniki:"));

        netto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        netto.setText("Wartość netto:");

        brutto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        brutto.setText("Wartość brutto:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Dominujący parametr:");

        nameSR.setText("Nazwa:");

        valueSRField.setText("Współczynnik wrażliwości:");

        jLabel5.setText("Podatek [%]:");

        tax.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                taxStateChanged(evt);
            }
        });

        overheadLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        overheadLabel.setText("Narzut:");

        marginLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        marginLabel.setText("Marża:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(brutto)
                            .addComponent(jLabel10)
                            .addComponent(nameSR)
                            .addComponent(valueSRField)
                            .addComponent(netto)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tax, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(overheadLabel)
                            .addComponent(marginLabel))
                        .addGap(0, 124, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(netto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brutto)
                .addGap(13, 13, 13)
                .addComponent(overheadLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(marginLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nameSR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valueSRField))
        );

        Plik.setText("Plik");

        Nowy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        Nowy.setText("Nowy");
        Nowy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NowyActionPerformed(evt);
            }
        });
        Plik.add(Nowy);

        Open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        Open.setText("Otwórz");
        Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenActionPerformed(evt);
            }
        });
        Plik.add(Open);

        Zapisz.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        Zapisz.setText("Zapisz");
        Zapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZapiszActionPerformed(evt);
            }
        });
        Plik.add(Zapisz);

        Wyjście.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        Wyjście.setText("Wyjście");
        Wyjście.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WyjścieActionPerformed(evt);
            }
        });
        Plik.add(Wyjście);

        jMenuBar1.add(Plik);

        Narzędzia.setText("Narzędzia");

        generujTabele.setText("Generuj zestawienie");
        Narzędzia.add(generujTabele);

        jMenuBar1.add(Narzędzia);

        Pomoc.setText("Pomoc");
        jMenuBar1.add(Pomoc);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        TableColumn col = new TableColumn();
        col = tableBOQ.getColumnModel().getColumn(4);

        try {
            listOfQuantity.getBillOfQuantity().add(new ComponentOfBOQ(nameField.getText(), unitField.getText(), Double.parseDouble(rateField.getText()), Double.parseDouble(quantityField.getText())));

            modelOfTable.addRow(new Object[]{nameField.getText(), unitField.getText(), df.format(Double.parseDouble(rateField.getText())), df.format(Double.parseDouble(quantityField.getText())), listOfQuantity.getBillOfQuantity().getLast().getOverhead(), df.format(listOfQuantity.getBillOfQuantity().getLast().getAmount())});
            genWW();

            refreshAmount();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Błędnie wprowadzone dane.\n\nError: " + e);
        }
        nameField.setText("");
        unitField.setText("");
        rateField.setText("");
        quantityField.setText("");
    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        selectedRow = tableBOQ.getSelectedRow();
        System.out.println("wybrano:" + selectedRow);
        try {
            if (tableBOQ.getSelectedRow() != -1) {
                deleteRow(selectedRow);

            }

        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Błędn zaznaczenie tablicy.\n\nError: " + e);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void WyjścieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WyjścieActionPerformed
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_WyjścieActionPerformed

    private void taxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_taxStateChanged
        // TODO add your handling code here:
        refreshAmount();
    }//GEN-LAST:event_taxStateChanged

    private void NowyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NowyActionPerformed
        // TODO add your handling code here:
        nameField.setText("");
        unitField.setText("");
        rateField.setText("");
        quantityField.setText("");
        clearTableBOQ();
        
    }//GEN-LAST:event_NowyActionPerformed

    private void ZapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZapiszActionPerformed
        // TODO add your handling code here:

        SaveToFile sv = new SaveToFile();
        JFileChooser choose = new JFileChooser();
        choose.showSaveDialog(null);
        String filePath = choose.getSelectedFile().getAbsolutePath();

        sv.saveList(listOfQuantity, filePath);
    }//GEN-LAST:event_ZapiszActionPerformed

    private void OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
        // TODO add your handling code here:
        JFileChooser choose = new JFileChooser();
        choose.showOpenDialog(null);
        String filePath = choose.getSelectedFile().getAbsolutePath();

        OpenFile op = new OpenFile();
        guard=1;
        clearTableBOQ();
        op.openFromFile(filePath, listOfQuantity);
        op.generateTableData(listOfQuantity, modelOfTable);
        guard=0;
        refreshAmount();

    }//GEN-LAST:event_OpenActionPerformed

    private void refreshAmount() {
        Integer taxMultiplier;
        taxMultiplier = (Integer) tax.getValue();
        netto.setText("Wartość netto:" + df.format(listOfQuantity.getTotalAmount())+" zł");
        brutto.setText("Wartość brutto:" + df.format(listOfQuantity.getTotalAmount() * (1 + taxMultiplier / 100.0))+" zł");

        nameSR.setText("Nazwa: " + listOfQuantity.getMaxElementBySR().getName());
        valueSRField.setText("Współczynnik wrażliwości : " + df.format(listOfQuantity.getMaxElementBySR().getSensitivityIndex()));
        
        overheadLabel.setText("Narzut: "+df.format(listOfQuantity.getGlobalOverhead())+"%");
        marginLabel.setText("Marża: "+df.format(listOfQuantity.getGlobalMargin())+"%");
    }

    private void genWW() {
        //Object[] listOfWW = new Object[listOfQuantity.getBillOfQuantity().size()];

        listOfQuantity.generateSR();

        for (int j = 0; j < listOfQuantity.getBillOfQuantity().size(); j++) {
            //listOfWW[j]=df.format(listOfQuantity.getBillOfQuantity().get(j).getSensitivityIndex());

            modelOfTable.setValueAt(df.format(listOfQuantity.getBillOfQuantity().get(j).getSensitivityIndex()), j, 6);
        }
    }

    private void deleteRow(int selection) throws ArrayIndexOutOfBoundsException {
        System.out.println(selection);
        modelOfTable.removeRow(selection);
        listOfQuantity.deleteElement(selection);
        genWW();
        refreshAmount();
    }

    private void clearTableBOQ() {
        int rows = modelOfTable.getRowCount();
        for (int i = 0; i < rows; i++) {
            deleteRow(0);
        }
    }

    private void refreshAmounts() {
        int i = 0;
        for (Iterator<ComponentOfBOQ> iterator = listOfQuantity.getBillOfQuantity().iterator(); iterator.hasNext();) {
            ComponentOfBOQ next = iterator.next();

            modelOfTable.setValueAt(df.format(listOfQuantity.getBillOfQuantity().get(i).getAmount()), i, 5);
            i++;
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Narzędzia;
    private javax.swing.JMenuItem Nowy;
    private javax.swing.JMenuItem Open;
    private javax.swing.JMenu Plik;
    private javax.swing.JMenu Pomoc;
    private javax.swing.JMenuItem Wyjście;
    private javax.swing.JMenuItem Zapisz;
    private javax.swing.JButton addButton;
    private javax.swing.JLabel brutto;
    private javax.swing.JButton delete;
    private javax.swing.JMenuItem generujTabele;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel marginLabel;
    private javax.swing.JTextArea nameField;
    private javax.swing.JLabel nameSR;
    private javax.swing.JLabel netto;
    private javax.swing.JLabel overheadLabel;
    private javax.swing.JTextField quantityField;
    private javax.swing.JTextField rateField;
    private javax.swing.JTable tableBOQ;
    private javax.swing.JSpinner tax;
    private javax.swing.JTextField unitField;
    private javax.swing.JLabel valueSRField;
    // End of variables declaration//GEN-END:variables
}
